config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  
  resources :users, only: [:new, :create] do
    resources :bookings, except: [:index, :show, :create, :new, :update, :edit, :destroy]
    get :bookings_index, path: 'bookings'
    get :bookings_show, path: 'bookings/:id'
  end 

  resources :sitters, only: [:index, :show, :new, :create, :update, :edit] do 
    resources :reviews, only: [:create, :destroy]
    resources :bookings, only: [:index, :new, :show, :create, :edit] do
      patch :accept
      patch :reject
      patch :complete
      patch :incomplete
      resources :booking_dates, only: [:new, :create] 
    end
    resources :availabilities, only: [:create, :destroy]
  end 
  
  resources :sessions, path: 'login', only: [:new, :create]
  resources :sessions, path: 'logout', only: [:destroy]
  
end

app/models/booking.rb
class Booking < ApplicationRecord
    mount_uploader :dog_avatar, DogAvatarUploader

    has_many :booking_dates
    belongs_to :user
    belongs_to :sitter
    
    validates :user_id, :sitter_id, :dog_breed, :dog_size, :dog_age, :dog_gender, :dog_name, :status, presence: true
    validates :dog_age, numericality: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @sitter = Sitter.find(params[:sitter_id])
    @user = current_user
    @booking = Booking.new
  end

  def create
    @sitter = Sitter.find params[:sitter_id]
    @user = User.find_by(email: params[:booking][:email])

    @booking = Booking.new(booking_params)
    @booking.status = 'Pending'

    if @booking.save
      redirect_to new_sitter_booking_booking_date_path(@sitter.id, @booking.id), notice: 'The booking request has been sent to the sitter'
    else
      render :new
    end
  end

  def index
    #GET sitter_booking route

    if current_sitter 
      @sitter = Sitter.find(params[:sitter_id])
      @owner = User.find_by(params[:user_id])
      @bookings = Booking.where(sitter_id: @sitter.id).order(updated_at: :desc)
      if current_sitter != @sitter
        redirect_to sitters_path
      end
    else
      redirect_to sitters_path
    end 

  end

  def accept
    @booking = Booking.find_by(id: params[:booking_id])
    @booking.update!(:status => 'Accepted')
    @booking_dates = BookingDate.where(booking_id: @booking.id)
    @booking_dates.each do |booking_date|
      if Availability.find_by(avail_date: booking_date.date, sitter_id: @booking.sitter_id)
        Availability.find_by(avail_date: booking_date.date, sitter_id: @booking.sitter_id).destroy
      end
    end
    redirect_to sitter_bookings_path(@booking.sitter_id)
  end
  
  def reject
    @booking = Booking.find_by(id: params[:booking_id])
    @booking.update!(:status => 'Rejected')
    redirect_to sitter_bookings_path(@booking.sitter_id)
  end

  def complete
    @booking = Booking.find_by(id: params[:booking_id])
    @booking.update!(:status => 'Completed')
    redirect_to sitter_bookings_path(@booking.sitter_id)
  end

  def incomplete
    @booking = Booking.find_by(id: params[:booking_id])
    @booking.update!(:status => 'Incomplete')
    redirect_to sitter_bookings_path(@booking.sitter_id)
  end

  def show
    @booking = Booking.find_by(id: params[:id])
    @owner = User.find_by(id: @booking.user_id)
    @booking_dates = BookingDate.where(booking_id: @booking.id)

  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(
        :dog_name,
        :dog_breed, 
        :dog_size, 
        :dog_age, 
        :dog_gender, 
        :dog_avatar,
        :info,
      ).merge(user_id:@user.id, sitter_id:@sitter.id)
    end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<div class="main">
  <div class="container">
    <div class="row-scroll">
      <div class="col-sm-5 col-sm-offset-1 mb-sm-40">
        <h4 class="font-alt">Booking Form</h4>
        <hr class="divider-w mb-10">     
        <%= form_for @booking, as: :booking, url: sitter_bookings_path(params[:sitter_id]), class: "form" do |form| %>

					<div>
					<% if @booking.errors.any? %>
						<div class="alert alert-danger" role="alert"> 
							<button class="close" type="button" data-dismiss="alert" aria-hidden="true">x</button>
							<% @booking.errors.full_messages.each do |error| %>
								<div>
									<i class="fa fa-cog fa-spin"></i>
									<strong>Alert!</strong>
									<%= error %>
								</div>
							<% end %>
						</div>
					<% end %>
					</div>

					<% if current_user %>
						<div class="form-group">
							<%= form.label :name do %>
							<i class="fa fa-id-badge" aria-hidden="true"></i>
							Name
							<% end %>
							<%= form.text_field :name , :value => "#{@user.first_name} #{@user.last_name}", class: 'form-control' %>
						</div>

						<div class="form-group">
							<%= form.label :email do %>
							<i class="fa fa-envelope" aria-hidden="true"></i>
							Email
							<% end %>
							<%= form.text_field :email, :value => "#{@user.email}", class: 'form-control'%>
						</div>

						<div class="form-group">
							<%= form.label :dog_name do %>
							<i class="fa fa-heart" aria-hidden="true"></i>
							Dog Name
							<% end %>
							<%= form.text_field :dog_name, class: 'form-control'%>
						</div>

						<div class="form-group">
							<%= form.label :dog_breed do %>
							<i class="fa fa-certificate"></i>
							Dog Breed
							<% end %>
							<%= form.text_field :dog_breed, class: 'form-control'%>
						</div>

						<div class="form-group">
							<%= form.label :dog_size do %>
							<i class="fa fa-sliders fa-6" aria-hidden="true"></i>
							Dog Size
							<% end %>
							<%= form.select :dog_size, ["Small (0 - 15lbs)", "Medium (16 - 40lbs)", "Large (41 - 100lbs)", "Giant (101+lbs)"], {}, class: 'form-control'%>
						</div>

						<div class="form-group">
							<%= form.label :dog_age do %>
							<i class="fa fa-birthday-cake" aria-hidden="true"></i>
							Dog Age
							<% end %>
							<%= form.text_field :dog_age, class: 'form-control'%>
						</div>

						<div class="form-group" >
							<%= form.label :dog_gender do %>
							<i class="fa fa-mars" aria-hidden="true"></i>
							Dog Gender
							<i class="fa fa-venus" aria-hidden="true"></i>							
							<% end %>
							<br>
							<%= form.select :dog_gender, ["Male", "Female"], {}, class: 'form-control' %>
						</div>

						<div class="form-group">
							<%= form.label :dog_avatar do %>
							<i class="fa fa-paw" aria-hidden="true"></i>
							Dog Avatar
							<% end %>
							<%= form.file_field :dog_avatar, class: 'form-control' %>
						</div>

						<div class="form-group">
							<%= form.label :info do %>
							<i class="fa fa-info-circle" aria-hidden="true"></i>
							Other Information
							<% end %>
							<%= form.text_area :info, class: 'form-control', placeholder: 'Optional'%>
						</div>
					
						<div class="form-group">
								<%= form.submit 'Submit', class: 'btn btn-block btn-round btn-b' %>
						</div>

						<br>
						<br>
						<br>
							
					<% else %>

						<br> 
						<h5 class="font-alt">Please login or register first</h5> 
						<br>

						<div class="col-sm-5 col-sm-offset-1 mb-sm-40">
								<%= link_to '<button class="btn btn-g btn-round btn-block" type="button">Login</button>'.html_safe, new_session_path %> 
								<br>
								<%= link_to '<button class="btn btn-g btn-round btn-block" type="button">Sign Up</button>'.html_safe, new_user_path %>
						</div>

					<% end %>

        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="main">
  <div class="container">
    <div class="row-scroll">
			<div class="col-sm-9 col-sm-offset-1 mb-sm-40">
				<h4 class="font-alt mb-0">Incoming Booking Requests</h4>
				<hr class="divider-w mt-10 mb-20">
				
				<% if !(@bookings.empty?) %> 
				
				<div role="tabpanel">

					<ul class="nav nav-tabs font-alt" role="tablist">
						<li class="active">
							<a href="#s-pending" data-toggle="tab" aria-expanded="true">Pending</a>
						</li>
						<li class="">
							<a href="#s-accepted" data-toggle="tab" aria-expanded="false">Accepted</a>
						</li>
						<li class="">
							<a href="#s-completed" data-toggle="tab" aria-expanded="true">Completed</a>
						</li>
						<li class="">
							<a href="#s-incomplete" data-toggle="tab" aria-expanded="true">Incomplete</a>
						</li>
					</ul>
					
					<div class="tab-content">

						<div class="sitter-pending tab-pane active" id="s-pending">							
							<% @bookings.each do |booking| %>
								<% if booking.status == 'Pending' %>
									<div class="card">
										<% @owner = User.find_by(id: booking.user_id) %>
                                            
											<div class="card-header font-alt">
												Request Made by: <%= "#{@owner.first_name} #{@owner.last_name}" %>
												<%= link_to '<button class="btn btn-danger btn-circle btn-xs" type="button"><i class="fa fa-times" aria-hidden="true"></i>Reject</button>'.html_safe, sitter_booking_reject_path(params[:sitter_id], booking.id), method: :patch %>
												<%= link_to '<button class="btn btn-success btn-circle btn-xs" type="button"><i class="fa fa-check" aria-hidden="true"></i>Accept</button>'.html_safe, sitter_booking_accept_path(params[:sitter_id], booking.id), method: :patch %>
											</div>
											<br>
											<div class="card-body">
                                                <div class="booking-avatar">
                                                    <span><%= image_tag(@owner.avatar.medium.url, class:"owner-avatar")%></span>
                                                    <span><%= image_tag(booking.dog_avatar.normal.url, class:"owner-avatar")%></span>
                                                </div>

												<strong class="font-alt">Dog Name: </strong>
												<h5 class="font-alt-regular"><%= booking.dog_name %></h5>
												<strong class="font-alt">Completed at: </strong>    
												<h5 class="font-alt-regular"><%= booking.updated_at.strftime("%Y-%m-%d at %I:%M%p") %> </h5>  
												<br>
												<%= link_to '<button class="btn btn-g btn-circle" type="button">Booking Details</button>'.html_safe, sitter_booking_path(params[:sitter_id], booking.id) %>
											</div>

									</div>
									<br>
								<% end %>
							<% end %>
						</div>

						<div class="sitter-accept tab-pane" id="s-accepted">
							<% @bookings.each do |booking| %>
								<% if booking.status == 'Accepted' %>
									<div class="card font-alt">
										<% @owner = User.find_by(id: booking.user_id) %>
										<div class="card-header">
											REQUEST MADE BY: <%= "#{@owner.first_name} #{@owner.last_name}" %>
											<%= link_to '<button class="btn btn-danger btn-circle btn-xs" type="button"><i class="fa fa-times" aria-hidden="true"></i>Incomplete</button>'.html_safe, sitter_booking_incomplete_path(params[:sitter_id], booking.id), method: :patch %>
											<%= link_to '<button class="btn btn-primary btn-circle btn-xs" type="button"><i class="fa fa-check" aria-hidden="true"></i>Complete</button>'.html_safe, sitter_booking_complete_path(params[:sitter_id], booking.id), method: :patch %>
										</div>
										<br>
										<div class="card-body">
                                            <div class="booking-avatar">
                                                <span><%= image_tag(@owner.avatar.medium.url, class:"owner-avatar")%></span>
                                                <span><%= image_tag(booking.dog_avatar.normal.url, class:"owner-avatar")%></span>
                                            </div>

											<strong class="font-alt">Dog Name: </strong>
											<h5 class="font-alt-regular"><%= booking.dog_name %></h5>
											<strong class="font-alt">Completed at: </strong>    
											<h5 class="font-alt-regular"><%= booking.updated_at.strftime("%Y-%m-%d at %I:%M%p") %> </h5>        
											<br>
											<%= link_to '<button class="btn btn-g btn-circle" type="button">Booking Details</button>'.html_safe, sitter_booking_path(params[:sitter_id], booking.id) %>
										</div>

									</div>
									<br>
								<% end %>
							<% end %>
						</div>

						<div class="sitter-complete tab-pane" id="s-completed">
							<% @bookings.each do |booking| %>
								<% if booking.status == 'Completed' %>
									<div class="card font-alt">
										<% @owner = User.find_by(id: booking.user_id) %>
										<div class="card-header">
											REQUEST MADE BY: <%= "#{@owner.first_name} #{@owner.last_name}" %></p>   
										</div>
										<br>
										<div class="card-body">
                                            <div class="booking-avatar">
                                                <span><%= image_tag(@owner.avatar.medium.url, class:"owner-avatar")%></span>
                                                <span><%= image_tag(booking.dog_avatar.normal.url, class:"owner-avatar")%></span>
                                            </div>
											<strong class="font-alt">Dog Name: </strong>
											<h5 class="font-alt-regular"><%= booking.dog_name %></h5>
											<strong class="font-alt">Completed at: </strong>    
											<h5 class="font-alt-regular"><%= booking.updated_at.strftime("%Y-%m-%d at %I:%M%p") %> </h5> 
											<br>
											<%= link_to '<button class="btn btn-g btn-circle" type="button">Booking Details</button>'.html_safe, sitter_booking_path(params[:sitter_id], booking.id) %>
										</div>
									</div>
								<% end %>
							<% end %>
						</div>

						<div class="sitter-incomplete tab-pane" id="s-incomplete">
							<% @bookings.each do |booking| %>
								<% if booking.status == 'Incomplete' || booking.status == 'Rejected' %>  
									<% @owner = User.find_by(id: booking.user_id) %>  
										<div class="card font-alt"> 
											<div class="card-header">
											REQUEST MADE BY: <%= "#{@owner.first_name} #{@owner.last_name}" %></p>    
											</div>
											<br>
											<div class="card-body">
                                                <div class="booking-avatar">
                                                    <span><%= image_tag(@owner.avatar.medium.url, class:"owner-avatar")%></span>
                                                    <span><%= image_tag(booking.dog_avatar.normal.url, class:"owner-avatar")%></span>
                                                </div>
												<strong class="font-alt">Dog Name: </strong>
												<h5 class="font-alt-regular"><%= booking.dog_name %></h5>
												<strong class="font-alt">Completed at: </strong>    
												<h5 class="font-alt-regular"><%= booking.updated_at.strftime("%Y-%m-%d at %I:%M%p") %> </h5>       
												<br>
												<%= link_to '<button class="btn btn-g btn-circle" type="button">Booking Details</button>'.html_safe, sitter_booking_path(params[:sitter_id], booking.id) %>
											</div>
										</div>
								<% end %>
							<% end %>
						</div>
					</div>
				</div>

				<% else %>
					<div class="alert alert-danger" role="alert">
					Currently, there is no booking.
					</div>
				<% end %>

                <br>
                <br>
                <br>

			</div>
		</div>
	</div>
</div>

app/views/bookings/new.html.erb
<%= render 'form' %>

app/views/bookings/show.html.erb
<div class="main">
  <div class="container">
    <div class="row-scroll">

      <div class="sitter-booking-details">
        <h5 class="font-alt">Booking Details Page</h5>
        <hr class="divider-w mb-10">
        <hr class="divider-w mb-10">
        
        <h5 class="font-alt mb-0" style="font-weight:bold">Owner:</h5>
         <%= image_tag(@owner.avatar.medium.url, class:"owner-avatar")%>
        <p class="font-alt"><%= "#{@owner.first_name} #{@owner.last_name}" %></p>  

        <h5 class="font-alt" style="font-weight:bold">Dog Name:</h5>
        <%= image_tag(@booking.dog_avatar.normal.url, class: "dog-avatar")%>
        <p class="font-alt"><%= @booking.dog_name %></p> 

        <h5 class="font-alt" style="font-weight:bold">Dog Breed:</h5>
        <p class="font-alt"><%= @booking.dog_breed %></p>

        <h5 class="font-alt" style="font-weight:bold">Dog Size:</h5>
        <p class="font-alt"><%= @booking.dog_size %></p>

        <h5 class="font-alt" style="font-weight:bold">Dog Age:</h5>
        <p class="font-alt"><%= @booking.dog_age %></p>

        <h5 class="font-alt" style="font-weight:bold">Dog Gender:</h5>
        <p class="font-alt"><%= @booking.dog_gender %></p> 

        <h5 class="font-alt" style="font-weight:bold">Other Info:</h5>
        <p class="font-alt"><%= @booking.info %></p>

        <h5 class="font-alt" style="font-weight:bold">Booking Dates:</h5>
        <% @booking_dates.each do |date|  %>
          <p class="font-alt"><%= date.date %></p>
        <% end %>

        <h5 class="font-alt" style="font-weight:bold">Booking Status:</h5>
        <p class="font-alt"><%= @booking.status %></p>   

        <%= link_to '<button class="btn btn-g btn-round " type="button">Back</button>'.html_safe, sitter_bookings_path %>
        <br>
        <br>
      </div>
      <br>
      <br>
    </div>
  </div>
</div>