config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  
  resources :users, only: [:new, :create] do
    resources :bookings, except: [:index, :show, :create, :new, :update, :edit, :destroy]
    get :bookings_index, path: 'bookings'
    get :bookings_show, path: 'bookings/:id'
  end 

  resources :sitters, only: [:index, :show, :new, :create, :update, :edit] do 
    resources :reviews, only: [:create, :destroy]
    resources :bookings, only: [:index, :new, :show, :create, :edit] do
      patch :accept
      patch :reject
      patch :complete
      patch :incomplete
      resources :booking_dates, only: [:new, :create] 
    end
    resources :availabilities, only: [:create, :destroy]
  end 
  
  resources :sessions, path: 'login', only: [:new, :create]
  resources :sessions, path: 'logout', only: [:destroy]
  
end

app/models/user.rb
class User < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	
	has_many :bookings
	has_many :sitters, through: :bookings

  has_secure_password
	before_validation :downcase_email

	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true, uniqueness: true, :case_sensitive => false
	validates :password, :password_confirmation, length: { minimum: 4 }

	def authenticate_with_credentials(email, password)
		if User.find_by(email: email.downcase.strip).try(:authenticate, password)
			@user = User.find_by_email(email.downcase.strip)
		else
			nil
		end
	end

	private

	def downcase_email
		self.email = email.downcase if email.present?
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to sitters_path
    else
      render :new
    end
  end

  def bookings_index
    #GET user_booking route
    if current_user
      @user = User.find(params[:user_id])
      @bookings = Booking.where(user_id: current_user.id).order(created_at: :desc)
      
      @bookings.each do |booking|
        @sitter = Sitter.find_by(id: booking.sitter_id)
        
      end

      if current_user != @user
        redirect_to sitters_path
      end
    else
      redirect_to sitters_path
    end 
  end

  def bookings_show
    @booking = Booking.find_by(id: params[:id])
    @sitter = Sitter.find_by(id: @booking.sitter_id)
    @sitter_user = User.find_by(id: @sitter.user_id)
    @owner = User.find_by(id: params[:user_id])
    @booking_dates = BookingDate.where(booking_id: @booking.id)
  end


  private
    def user_params
      params.require(:user).permit(
        :first_name, :last_name, :email, :password, :password_confirmation, :avatar
      )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/bookings_index.html.erb
<div class="main">
  <div class="container">
    <div class="row-scroll">
			<div class="col-sm-9 col-sm-offset-1 mb-sm-40">
				<h4 class="font-alt mb-0">User's Booking Status</h4>
				<hr class="divider-w mt-10 mb-20">
				<% if !(@bookings.empty?) %> 
				<div role="tabpanel">

					<ul class="nav nav-tabs font-alt" role="tablist">
						<li class="active">
							<a href="#u-pending" data-toggle="tab" aria-expanded="true">Pending</a>
						</li>
						<li class="">
							<a href="#u-accepted" data-toggle="tab" aria-expanded="false">Accepted</a>
						</li>
						<li class="">
							<a href="#u-completed" data-toggle="tab" aria-expanded="true">Completed</a>
						</li>
						<li class="">
							<a href="#u-incomplete" data-toggle="tab" aria-expanded="true">Incomplete</a>
						</li>
					</ul>
					
					<div class="tab-content">

						<div class="user-pending tab-pane active" id="u-pending">							
							<% @bookings.each do |booking| %>
								<% if booking.status == 'Pending' %>
								<div class="card">
								<% @sitter_of_booking = Sitter.find_by(id: booking.sitter_id) %>
									<div class="card-header font-alt">
									Sitter Name: <%= @sitter_of_booking.name %>   
									</div>
									<br>

									<div class="card-body">
                                        <div class="booking-avatar">
										<% @sitter_user = User.find_by(id: @sitter_of_booking.user_id) %>
                                            <span><%= link_to image_tag(@sitter_user.avatar.medium.url, class:"sitter-avatar"), sitter_path(@sitter_of_booking.id)%></span>
                                            <span><%= image_tag(booking.dog_avatar.normal.url, class:"sitter-avatar")%></span>
                                        </div>
										<strong class="font-alt">Dog Name: </strong>
										<h5 class="font-alt-regular"><%= booking.dog_name %></h5>
										<strong class="font-alt">Sent at: </strong>  
										<h5 class="font-alt-regular"><%= booking.created_at.strftime("%Y-%m-%d at %I:%M%p") %></h5>
										<br>
										<%= link_to '<button class="btn btn-g btn-circle" type="button">Booking Details</button>'.html_safe, user_bookings_show_path(params[:user_id], booking.id) %>
									</div>
								</div>
								<br>
								<% end %>
							<% end %>
						</div>

						<div class="user-accept tab-pane" id="u-accepted">
							<% @bookings.each do |booking| %>
								<% if booking.status == 'Accepted' %>
								<div class="card font-alt">
								<% @sitter_of_booking = Sitter.find_by(id: booking.sitter_id) %>
									
									<div class="card-header">
									Sitter Name: <%= @sitter_of_booking.name %>
									</div>
									<br>
									<div class="card-body">
                                        <div class="booking-avatar">
										<% @sitter_user = User.find_by(id: @sitter_of_booking.user_id) %>
                                            <span><%= link_to image_tag(@sitter_user.avatar.medium.url, class:"sitter-avatar"), sitter_path(@sitter_of_booking.id)%></span>
											<span><%= image_tag(booking.dog_avatar.normal.url, class:"sitter-avatar")%></span>
                                        </div>
										<strong class="font-alt">Dog Name: </strong>
										<h5 class="font-alt-regular"><%= booking.dog_name %></h5>
										<strong class="font-alt">Sent at: </strong>  
										<h5 class="font-alt-regular"><%= booking.created_at.strftime("%Y-%m-%d at %I:%M%p") %></h5> 
										<br>
										<%= link_to '<button class="btn btn-g btn-circle" type="button">Booking Details</button>'.html_safe, user_bookings_show_path(params[:user_id], booking.id) %>
									</div>
								</div>
								<br>
								<% end %>
							<% end %>
						</div>

						<div class="user-complete tab-pane" id="u-completed">
							<% @bookings.each do |booking| %>
								<% if booking.status == 'Completed' %>
								<div class="card font-alt">
								<% @sitter_of_booking = Sitter.find_by(id: booking.sitter_id) %>
									<div class="card-header">
										Sitter Name: <%= @sitter_of_booking.name %></p>     
									</div>
									<br>
									<div class="card-body">
                                        <div class="booking-avatar">
										<% @sitter_user = User.find_by(id: @sitter_of_booking.user_id) %>
                                            <span><%= link_to image_tag(@sitter_user.avatar.medium.url, class:"sitter-avatar"), sitter_path(@sitter_of_booking.id)%></span>
                                            <span><%= image_tag(booking.dog_avatar.normal.url, class:"sitter-avatar")%></span>
                                        </div>										
										<strong class="font-alt">Dog Name: </strong>
										<h5 class="font-alt-regular"><%= booking.dog_name %></h5>
										<strong class="font-alt">Sent at: </strong>  
										<h5 class="font-alt-regular"><%= booking.created_at.strftime("%Y-%m-%d at %I:%M%p") %></h5>   
										<br>
										<%= link_to '<button class="btn btn-g btn-circle" type="button">Booking Details</button>'.html_safe, user_bookings_show_path(params[:user_id], booking.id) %>
									</div>
								</div>
								<br>
								<% end %>
							<% end %>
						</div>

						<div class="user-incomplete tab-pane" id="u-incomplete">
							<% @bookings.each do |booking| %>
								<% if booking.status == 'Incomplete' || booking.status == 'Rejected' %>  
									<% @sitter_of_booking = Sitter.find_by(id: booking.sitter_id) %>
								<div class="card font-alt">
									<div class="card-header">
										Sitter Name: <%= @sitter_of_booking.name %>      
									</div>
									<br>
									<div class="card-body">
                                        <div class="booking-avatar">
										<% @sitter_user = User.find_by(id: @sitter_of_booking.user_id) %>
                                            <span><%= link_to image_tag(@sitter_user.avatar.medium.url, class:"sitter-avatar"), sitter_path(@sitter_of_booking.id)%></span>
                                            <span><%= image_tag(booking.dog_avatar.normal.url, class:"sitter-avatar")%></span>
                                        </div>										
										<strong class="font-alt">Dog Name: </strong>
										<h5 class="font-alt-regular"><%= booking.dog_name %></h5>
										<strong class="font-alt">Sent at: </strong>  
										<h5 class="font-alt-regular"><%= booking.created_at.strftime("%Y-%m-%d at %I:%M%p") %></h5>        
										<br>
										<%= link_to '<button class="btn btn-g btn-circle" type="button">Booking Details</button>'.html_safe, user_bookings_show_path(params[:user_id], booking.id) %>
									</div>
								</div>
								<br>
								<% end %>
							<% end %>
						</div>
					</div>

				</div>

				<% else %>
					<div class="alert alert-danger" role="alert">
					Currently, there is no booking
					</div>
				<% end %>

                <br>
                <br>
                <br>
                
			</div>
		</div>
	</div>
</div>

app/views/users/bookings_show.html.erb
<div class="main">
  <div class="container">
    <div class="row-scroll">

      <div class="user-booking-details">
        <h4 class="font-alt">Booking Details Page</h4>
          <hr class="divider-w mb-10">
          <hr class="divider-w mb-10">

        <h5 class="font-alt mb-0" style="font-weight:bold">Sitter:</h5>
        <%= image_tag(@sitter_user.avatar.medium.url, class:"sitter-avatar")%>
        <p class="font-alt"><%= @sitter.name %></p>
        <h5 class="font-alt" style="font-weight:bold">Dog Name:</h5>
        <%= image_tag(@booking.dog_avatar.normal.url, class: "dog-avatar")%>
        <p class="font-alt"><%= @booking.dog_name %></p> 
        <h5 class="font-alt" style="font-weight:bold">Dog Name:</h5>
        <p class="font-alt"><%= @booking.dog_name %></p> 
        <h5 class="font-alt" style="font-weight:bold">Dog Breed:</h5>
        <p class="font-alt"><%= @booking.dog_breed %></p>
        <h5 class="font-alt" style="font-weight:bold">Dog Size:</h5>
        <p class="font-alt"><%= @booking.dog_size %></p>
        <h5 class="font-alt" style="font-weight:bold">Dog Age:</h5>
        <p class="font-alt"><%= @booking.dog_age %></p>
        <h5 class="font-alt" style="font-weight:bold">Dog Gender:</h5>
        <p class="font-alt"><%= @booking.dog_gender %></p>  
        <h5 class="font-alt" style="font-weight:bold">Other Info:</h5>
        <p class="font-alt"><%= @booking.info %></p>
        <h5 class="font-alt" style="font-weight:bold">Booking Status:</h5>
        <p class="font-alt"><%= @booking.status %></p>    
        <h5 class="font-alt" style="font-weight:bold">Booking Dates:</h5>
        <% @booking_dates.each do |date|  %>
          <p class="font-alt"><%= date.date %></p>
        <% end %>
      </div>
      <br>
      <br>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main">
	<div class="container">
		<div class="row-scroll">
            <div class="col-sm-5 col-sm-offset-1 mb-sm-40">
                <h4 class="font-alt">Register</h4>
                <hr class="divider-w mb-10">
                
                <%= form_for :user, url: '/users', class: "form" do |form| %>

                <div>
                <% if @user.errors.any? %>
                    <div class="alert alert-danger" role="alert"> 
                        <button class="close" type="button" data-dismiss="alert" aria-hidden="true">x</button>
                        <% @user.errors.full_messages.each do |error| %>
                            <div>
                                <i class="fa fa-cog fa-spin"></i>
                                <strong>Alert!</strong>
                                <%= error %>
                            </div>
                        <% end %>
                    </div>
                <% end %>
                </div>
                
                <div class="form-group">
                    <%= form.label :first_name do %>
                    <i class="fa fa-id-badge" aria-hidden="true"></i>
                    First Name
                    <% end %>
                    <%= form.text_field :first_name, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= form.label :last_name do %>
                    <i class="fa fa-id-badge" aria-hidden="true"></i>
                    Last Name
                    <% end %>
                    <%= form.text_field :last_name, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= form.label :email do %>
                    <i class="fa fa-envelope" aria-hidden="true"></i>
                    Email
                    <% end %>
                    <%= form.text_field :email, class: 'form-control' %>
                </div>
            
                <div class="form-group">
                    <%= form.label :password do %>
                    <i class="fa fa-unlock-alt" aria-hidden="true"></i>
                    Password
                    <% end %>
                    <%= form.password_field :password, class: 'form-control' %>
                </div>
            
                <div class="form-group">
                    <%= form.label :password_confirmation do %>
                    <i class="fa fa-unlock-alt" aria-hidden="true"></i>
                    Password Confirmation
                    <% end %>
                    <%= form.password_field :password_confirmation, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= form.label :avatar do %>
                    <i class="fa fa-user" aria-hidden="true"></i>
                    Avatar
                    <% end %>
                    <%= form.file_field :avatar, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= form.submit 'Register', class: 'btn btn-block btn-round btn-b' %>
                </div>
                <br>
                <br>
                <br>

                <% end %>
            </div>
		</div>
	</div>
</div>