config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  
  resources :users, only: [:new, :create] do
    resources :bookings, except: [:index, :show, :create, :new, :update, :edit, :destroy]
    get :bookings_index, path: 'bookings'
    get :bookings_show, path: 'bookings/:id'
  end 

  resources :sitters, only: [:index, :show, :new, :create, :update, :edit] do 
    resources :reviews, only: [:create, :destroy]
    resources :bookings, only: [:index, :new, :show, :create, :edit] do
      patch :accept
      patch :reject
      patch :complete
      patch :incomplete
      resources :booking_dates, only: [:new, :create] 
    end
    resources :availabilities, only: [:create, :destroy]
  end 
  
  resources :sessions, path: 'login', only: [:new, :create]
  resources :sessions, path: 'logout', only: [:destroy]
  
end

app/models/sitter.rb
class Sitter < ApplicationRecord
	mount_uploaders :photos, PhotoUploader

    has_many :availabilities
    has_many :bookings
    has_many :users, through: :bookings
    has_many :reviews
    belongs_to :user
    
    validates :name, :address, :summary, :rules, :user_id, presence: true
    validates :price, numericality: true
    
    geocoded_by :address
    after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
    
end

app/controllers/sitters_controller.rb
class SittersController < ApplicationController
  
  def index
    @sitters = Sitter.all.order(created_at: :desc)
    
  end

  def show
    @user = current_sitter
    avails = Availability.where(sitter_id: params[:id])
    @dates = Array.new
    avails.each do |date|
      @dates.push(date.avail_date).sort!
    end
    @sitter = Sitter.find params[:id]
    @photos = @sitter.photos
    @reviews = Review.where(sitter_id: @sitter.id)
  end

  def new
    @sitter = Sitter.new
    @user = current_user
    if current_sitter 
      redirect_to sitter_path(current_sitter.id) 
    end 
  end

  def create
    @user = current_user
    @sitter = Sitter.new(sitter_params)
    @sitter.user_id = @user.id
    
    if @sitter.save
      redirect_to sitter_path(@sitter.id), notice: 'New sitter created!'
    else
      render :new
    end
  end

  def edit 
    @user = current_user
    if current_sitter 
      @sitter = Sitter.find(params[:id])
    end
  end

  def update
    @sitter = Sitter.find(params[:id])
    if @sitter.update(sitter_params)
      redirect_to @sitter
    else
      render :edit
    end 
  end


  private

  def sitter_params
    params.require(:sitter).permit(
      :name,
      :address,
      :summary,
      :rules,
      :price,
      {photos: []}
    )
  end

end

app/helpers/sitters_helper.rb
module SittersHelper
end

app/views/sitters/_sitter.html.erb
<article class="sitter">
  <%= link_to sitter do %>
  <div>    
    <ul class="text-center">
      <li>
        <h3> <%= sitter.name %></h3>
      </li>

      <%  @user = User.find_by(id: sitter.user_id) %>
      <li>
        <%= image_tag(@user.avatar.medium.url, class:'sitter-avatar') %>
      </li>
      <br>
      <% end  %>

      <li>
        <% @average = Review.where(sitter_id: sitter.id).average(:rating) %>
        <% @average.to_i.times do %>
        ⭐️
        <% end %>
      </li>

      <li style="font-size: 18px">  
        <%= sitter.summary %>
      </li>
    </ul>
    
    <footer class="card text-center">
			<h2><i class="fa fa-usd" aria-hidden="true"></i> <%= sitter.price %> / night <h2>
			
			<%= link_to sitter, class: 'btn btn-default pull-center' do %>
				Details
			<% end %>
    </footer>
  </div>
</article>

app/views/sitters/edit.html.erb
<div class="main">
  <div class="container">
    <div class="row-scroll">
        <div class="col-sm-5 col-sm-offset-1 mb-sm-40">
            <h4 class="font-alt">Update Sitter Information</h4>
            <hr class="divider-w mb-10">     

            <script> ReactRailsUJS.mountComponents()</script>
              <div style="text-align: center">
                <%= react_component("Calendar", {sitter: @sitter.id}, {prerender: true}) %>
              </div>
            <br>

            <%= form_for :sitter, url: "/sitters/#{@sitter.id}", method: :put, class: "form" do |form| %>

            <div>
			  <% if @sitter.errors.any? %>
				<div class="alert alert-danger" role="alert"> 
				<button class="close" type="button" data-dismiss="alert" aria-hidden="true">x</button>
				<% @sitter.errors.full_messages.each do |error| %>
				  <div>
				    <i class="fa fa-cog fa-spin"></i>
				    <strong>Alert!</strong>
				    <%= error %>
				  </div>
				<% end %>
				</div>
        	  <% end %>
			</div>
            
            <div class="form-group">
                <%= form.label :name %>
                <%= form.text_field :name , :value => "#{current_user.first_name} #{current_user.last_name}", class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :address %>
                <%= form.text_field :address, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :summary %>
                <%= form.text_area :summary, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :rules %>
                <%= form.text_area :rules, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :price %>
                <%= form.text_field :price, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.submit 'Submit', class: 'btn btn-block btn-round btn-b' %>
            </div>
            <br>
            <br>
            <br>
            
            <% end %>
                
      </div>
    </div>
  </div>
</div>

app/views/sitters/index.html.erb
      <div class="main">
        <div class="container">
            <div class="row-scroll">
              <div class="sidebar-sitter-index">
                <div class="widget">
                <section class="sitter-index">
                  <h2 class="widget-title font-alt">Sitter Nearby</h2>
                  <ul class="widget-posts">
                  <li> <%= render @sitters %> </li>
                  </ul>
                </section>  
                </div>
              </div>
              <div class="col-sm-8 map-container">
                <div id="map">
                  <%= 
                  map(:center => {
                    :latlng => [49.2827290, -123.1207380],
                    :zoom => 14
                    })
                  %>
                </div>
              </div>
            </div>    
        </div>

<script type='text/javascript'>

  if (navigator.geolocation) {
	  navigator.geolocation.getCurrentPosition(function(position){
	  var latitude = position.coords.latitude;
	  var longitude = position.coords.longitude;
	  });

	  map.locate({setView: true, maxZoom: 14});
	  function onLocationFound(e) {

		L.marker(e.latlng).addTo(map)
    .bindPopup("You are here").openPopup();
    
    <% @sitters.each do |sitter| %>
    <% @user = User.find_by(id: sitter.user_id) %>
      L.marker([<%=sitter.latitude%>, <%=sitter.longitude%>]).addTo(map)
      .bindPopup("<a id='popup-link' href='sitters/<%=sitter.id%>'/> <img style='border-radius: 50%;' src=<%=@user.avatar.thumb.url%>/> \n<br/> <strong><%=sitter.name%></strong> \n<br/> <%=sitter.summary%> \n<br/> Price: $<%=sitter.price%>/night ");
    <% end %>
        
	  }
	  map.on('locationfound', onLocationFound);
  }else {
	  alert("Geolocation API is not supported in your browser. :(");
  }
</script>

app/views/sitters/new.html.erb
<div class="main">
  <div class="container">
    <div class="row-scroll">
        <div class="col-sm-5 col-sm-offset-1 mb-sm-40">
            <h4 class="font-alt">Become A Sitter</h4>
            <hr class="divider-w mb-10">     

            <%= form_for :sitter, url: sitters_path, class: "form" do |form| %>

            <div>
              <% if @sitter.errors.any? %>
                <div class="alert alert-danger" role="alert"> 
                <button class="close" type="button" data-dismiss="alert" aria-hidden="true">x</button>
                <% @sitter.errors.full_messages.each do |error| %>
                    <div>
                    <i class="fa fa-cog fa-spin"></i>
                    <strong>Alert!</strong>
                    <%= error %>
                    </div>
                <% end %>
                </div>
              <% end %>
            </div>

            <div class="form-group">
                <%= form.label :name do %>
                <i class="fa fa-id-badge" aria-hidden="true"></i>
                Name
                <% end %>
                <%= form.text_field :name , :value => "#{@user.first_name} #{@user.last_name}", class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :address do %>
                <i class="fa fa-address-card-o" aria-hidden="true"></i>
                Address
                <% end %>
                <%= form.text_field :address, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :summary do %>
                <i class="fa fa-info-circle" aria-hidden="true"></i>
                Summary
                <% end %>
                <%= form.text_area :summary, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :rules do %>
                <i class="fa fa-exclamation-circle" aria-hidden="true"></i>
                Rules
                <% end %>
                <%= form.text_area :rules, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :price do %>
                <i class="fa fa-usd" aria-hidden="true"></i>
                Price
                <% end %>
                <%= form.text_field :price, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :photos do %>
                <i class="fa fa-picture-o" aria-hidden="true"></i>
                Photos (Ctrl/Cmd + Select to choose multiple files)
                <% end %>
                <%= form.file_field :photos, multiple: true, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.submit 'Submit', class: 'btn btn-block btn-round btn-b' %>
            </div>
            
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sitters/show.html.erb
<div class="main">
    <div class="container">
        <div class="row-scroll">
            <div class="sidebar-sitter-details">
                <div class="widget">
                    <section class="sitter-index">
						<h3 class="font-alt mb-0"><%= @sitter.name %></h3>

						<ul class="widget-posts">
							<li>
							<%  @user = User.find_by(id: @sitter.user_id) %>
							<%= image_tag(@user.avatar.medium.url, class:'sitter-avatar')%>
							</li>
							<li class="ratings">
							<% @average = Review.where(sitter_id: @sitter.id).average(:rating) %>
							<span>
							<% @average.to_i.times do %>
							⭐️
							<% end %> 
							</span>    
									
							<span >&nbsp(<%= Review.where(sitter_id: @sitter.id).count %> Reviews)</span>
							</li>
						</ul>
						<br>
						<div>
							<h4 class="font-alt mb-0" style="font-weight:bold">Price</h4> 
								<hr class="divider-w mt-10 mb-20">                 
								<h4 class="font-alt mb-0"><i class="fa fa-usd" aria-hidden="true"></i><%= @sitter.price %>/night</h4>
						</div>
						<br>
						<script> ReactRailsUJS.mountComponents() </script>
						<div class="DayPicker" lang="en">
							<h4 class="font-alt mb-0" style="font-weight:bold">Availability</h4>
							<hr class="divider-w mt-10 mb-20">
							<%= react_component('Availability', {dates: @dates}, {prerender: true}) %>
							<% if current_user %> 
								<% if Sitter.find_by(user_id: current_user.id) == nil || (current_sitter.id != @sitter.id)%>
									<%= link_to '<button class="btn btn-border-d btn-round btn-block" type="button"><i class="fa fa-calendar" aria-hidden="true"></i>Booking</button>'.html_safe, new_sitter_booking_path(@sitter.id) %>    
								<% end %>
							<% else %>
								<div class="alert alert-info" role="alert">
									<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %> to make a booking with <%= @user.first_name %>!
								</div>      
							<% end%>
						</div>
						<br>
						<br>
						<br>
                    </section>
                </div>
            </div>
			<div class="col-sm-8 map-container">
				<h4 class="font-alt mb-0" style="font-weight:bold">Gallery</h4>
				<hr class="divider-w mt-10 mb-20">
				<div class="owl-carousel owl-theme owl-loaded">
					<% @photos.each do |photo| %>
						<%= image_tag photo.normal.url %>
					<% end %>
				</div>

				<div class="sitter-details">
					<h4 class="font-alt mb-0" style="font-weight:bold">Summary</h4>
					<hr class="divider-w mt-10 mb-20">
					<h8 class="font-alt-regular mb-0"><%= @sitter.summary %>
					Doggo ipsum the neighborhood pupper pats shoob long woofer you are doin me a concern long doggo, very hand that feed shibe extremely cuuuuuute borking doggo. Sub woofer floofs yapper blop pupperino pupper long doggo pupperino, big ol I am bekom fat adorable doggo he made many woofs long doggo. Many pats heckin floofs pats aqua doggo, snoot clouds. Extremely cuuuuuute big ol super chub you are doing me the shock fat boi, clouds fat boi. Pats tungg you are doing me the shock very good spot long bois, borkf blop long water shoob. He made many woofs I am bekom fat you are doing me a frighten waggy wags you are doing me a frighten maximum borkdrive, length boy pupper vvv. Doge woofer sub woofer he made many woofs doing me a frighten, what a nice floof yapper. Sub woofer much ruin diet borking doggo heckin angery woofer mlem porgo floofs, heckin good boys and girls puggorino dat tungg tho wow very biscit blep.</h8>
					<h4 class="font-alt mb-0" style="font-weight:bold">Rules</h4>   
					<hr class="divider-w mt-10 mb-20">               
					<h8 class="font-alt-regular mb-0">
					<ul>
					<li><%= @sitter.rules %></li>
					<li>ur givin me a spook. Such treat many pats such treat very good spot doing me a frighten most angery pupper I have ever seen, heckin angery woofer pupperino heckin good boys and girls. Pupperino puggorino sub woofer wow very biscit shoob waggy wags borking doggo, thicc extremely cuuuuuute you are doing me the shock shooberino. Lotsa pats heckin good boys wow such tempt such treat I am bekom fat, porgo what a nice floof floofs. pupperino floofs. Big ol pupper long bois length boy sub woofer, adorable doggo. Yapper smol borking doggo with a long snoot for pats porgo you are doin me a concern, snoot. Shibe stop it fren pats much ruin diet, long woofer. Stop it fren woofer stop it fren maximum borkdrive long doggo, snoot dat tungg tho. wow such tempt heck big ol pupper. Ruff woofer boofers bork sub woofer ruff ur givin me a spook pats, puggo such treat boof I am bekom fat ruff very hand that feed shibe.  Doggorino wow such tempt very good spot very jealous pupper blop, you are doing me the shock sub woofer. Shooberino pats very good spot noodle horse, blep.</li></h8>
					</ul>
				</div>

				<div>
				<h4 class="font-alt mb-0" style="font-weight:bold">Reviews</h4>
					
				<% if current_user && (current_sitter != @sitter) %>
					<hr class="divider-w mt-10 mb-20">
					<%= form_for :review, url: sitter_reviews_path(@sitter.id) do |f| %>
						<div class="form-group">
						<%= f.label "Rating:", class: 'font-alt'%> 
						<%= f.select :rating, options_for_select([["Select Rating", ""], 1, 2, 3, 4, 5 ])%>
						</div>
						<div class="form-group">
						<%= f.label "Description:", class: 'font-alt'%>
						<br>
						<%= f.text_area :content, placeholder: "Leave a comment", cols: "60", rows: "5" %>
						</div>
						<div class="form-group">
						<%= f.submit "Submit", class: "btn btn-round btn-b" %>
						</div>
					<% end %>
				</div>

				<% elsif current_sitter == @sitter %>
					<div>
					</div>
				
				<% else %>
					<hr class="divider-w mt-10 mb-20">
					<div class="alert alert-info" role="alert">
						Please <%= link_to "Log in", new_session_path %> to leave a review for <%= @user.first_name %>!
					</div>      
				<% end %>

				<div>
					<hr class="divider-w mt-10 mb-20">
					<% @reviews.reverse.each do |review| %>
						<% User.where(id: review.user_id).each do |user| %>
						<div class="well">
							<h8 class="font-alt">
								<%= image_tag user.avatar.thumb.url %>
								<%= user.first_name %>
								<div>
								<br>
								Rating:
								<p><% review.rating.times do %>
								⭐️
								<% end %>
								</p>
								</div>
							</h8>

							<div class="font-alt-regular mb-0">
								<h8 class="font-alt"> Description:  </h8>
								<p><%= review.content %></p>
							</div>

							<% if user == current_user %>
								<div>
								<br>
								<%= link_to 'Delete', "/sitters/#{@sitter.id}/reviews/#{review.id}", method: :delete, class: 'btn btn-danger btn-circle' %>
								</div>
							<% end %>

						</div>
						<% end %>
					<% end %>
				</div>
			<br>
			<br>
            </div>
        </div>    
    </div>
</div>

<script type="text/javascript">
    $('.owl-carousel').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
				items: 2,
				center: true,
				autoplay: true,
				autoplayHoverPause: true,
				navText: ['<i class="fa fa-chevron-left fa-2x"></i>', '<i class="fa fa-chevron-right fa-2x"></i>']
    })
</script>