config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  
  resources :users, only: [:new, :create] do
    resources :bookings, except: [:index, :show, :create, :new, :update, :edit, :destroy]
    get :bookings_index, path: 'bookings'
    get :bookings_show, path: 'bookings/:id'
  end 

  resources :sitters, only: [:index, :show, :new, :create, :update, :edit] do 
    resources :reviews, only: [:create, :destroy]
    resources :bookings, only: [:index, :new, :show, :create, :edit] do
      patch :accept
      patch :reject
      patch :complete
      patch :incomplete
      resources :booking_dates, only: [:new, :create] 
    end
    resources :availabilities, only: [:create, :destroy]
  end 
  
  resources :sessions, path: 'login', only: [:new, :create]
  resources :sessions, path: 'logout', only: [:destroy]
  
end

app/views/layouts/_foot_bar.html.erb
<footer class="footer bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <p class="copyright font-alt">&copy; 2018&nbsp;<a href="index.html">PAW2PAW</a> CS ML LT</p>
            </div>
            <div class="col-sm-6">
                <div class="footer-social-links">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                    <a href="#"><i class="fa fa-skype"></i></a>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <span class="icon-bar"></span><%= link_to image_tag("logos/logo.png", class:"navbar-logo"), root_path %>
    </div>
    <div class="collapse navbar-collapse" id="custom-collapse">
      <ul class="nav navbar-nav navbar-right">
      <li class="dropdown"><%= link_to '<i class="fa fa-search" aria-hidden="true"></i>Search'.html_safe, sitters_path %></li>
      <% if current_user && !current_sitter %>
      <li class="dropdown"><%= link_to '<i class="fa fa-paw" aria-hidden="true"></i>Become A Sitter'.html_safe, new_sitter_path %></li>
      <li class="dropdown"><%= link_to '<i class="fa fa-sign-out" aria-hidden="true"></i>Logout'.html_safe, session_path(current_user.id), method: :delete %></li>
      <li class="dropdown"><%= link_to current_user.first_name, user_bookings_index_path(current_user.id)%></li>
      <span><%= link_to image_tag(current_user.avatar.thumb.url, class:'navbar-avatar'), user_bookings_index_path(current_user.id)%></span>
      <% elsif current_sitter %>
        <li class="dropdown">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sitter Menu</a>
          <ul class="dropdown-menu">
           <li><%= link_to 'My Sitter Page', sitter_path(current_sitter.id) %></li>
           <li><%= link_to "Incoming Booking Requests", sitter_bookings_path(current_sitter.id) %></li>           
           <li><%= link_to 'Edit', edit_sitter_path(current_sitter.id) %></li>
          </ul>  
        </li>
      <li class="dropdown"><%= link_to '<i class="fa fa-sign-out" aria-hidden="true"></i>Logout'.html_safe, session_path(current_user.id), method: :delete %></li>
      <li class="dropdown"><%= link_to current_user.first_name, user_bookings_index_path(current_user.id) %></li>
      <span><%= link_to image_tag(current_user.avatar.thumb.url, class:'navbar-avatar'), user_bookings_index_path(current_user.id) %></span>
      <% else %>
        <li class="dropdown"><%= link_to '<i class="fa fa-sign-in" aria-hidden="true"></i>Login'.html_safe, new_session_path %></li>
        <li class="dropdown"><%= link_to '<i class="fa fa-user-plus" aria-hidden="true"></i>Sign Up'.html_safe, new_user_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paw2paw</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application' %>    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  
  <body>
    <main>
    <%= render 'layouts/top_nav' %>
    <%= yield %>
    </main>
    <%= render 'layouts/foot_bar' %>
  </body>
</html>